name: 'azcli'
description: 'Az cli spike'
inputs:
  inlineScript:  # id of input
    description: 'az cli command'
    required: true
  scriptPath:
    description: 'path of the script'
    required: false
  azcliversion:
    description: 'az cli version'
    required: false
    default: 'latest'
runs:
  using: 'node12'
  main: 'lib/init.js'