name: 'azcli'
description: 'Az cli spike'
inputs:
  creds:
    description: 'Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS'
    required: false
  sampleInput:  # id of input
    description: 'az cli command'
    required: true
    default: 'az account show'
  sampleObj:
    description: 'Sample object'
    required: false
  AZURE_SERVICE_APP_ID:
    required: true
  AZURE_SERVICE_PASSWORD:
    required: true
  AZURE_SERVICE_TENANT:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sampleInput }}
    - ${{ inputs.AZURE_SERVICE_APP_ID }}
    - ${{ inputs.AZURE_SERVICE_PASSWORD }}
    - ${{ inputs.AZURE_SERVICE_TENANT }}
    - ${{ inputs.sampleObj }}