# File: .github/workflows/az_login_v2.yml

on: [push]

name: Azure/CLI - the actual repo

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.Azure_cred_login_obj }}

    - name: Azure cli
      uses: azure/CLI@v1
      env: 
        showVariable: show
      with:
        azcliversion: 2.0.68
        inlineScript: |
          printenv
          az account $showVariable
          az storage -h
          
          
    - name: Azure cli
      uses: azure/CLI@v1.0.3
      env: 
        showVariable: show
      with:
        inlineScript: |
          printenv
          az account $showVariable
          az storage -h
        
