# File: .github/workflows/az_login_v2.yml

on: [push]

name: AzureCLIAction

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.Azure_cred_login_obj }}

    - run: |
        printenv
    - name: Checkout
      uses: actions/checkout@v1
    - run : |
        chmod +x ./sampleScript.sh
        ./sampleScript.sh
    - name: Az cli spike
      uses: ./spike-az-cli_2
      with:
        inlineScript: 'az account show ; az --version;pwd;ls'
        scriptPath: 'sampleScript.sh'
