# File: .github/workflows/az_login_v2.yml

on: [push]

name: AzureCLIAction

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/actions/login@v1
      with:
        creds: ${{ secrets.Azure_cred_login_obj }}

    - run: |
        printenv
    - run: |
        ls
    - name: Checkout
      uses: actions/checkout@v1
    - name: Az cli spike
      uses: ./spike-az-cli_2
      with:
        inlineScript: 'az account show | az --version'
    - run: |
        pwd
    - run: |
        tree GITHUB_REPOSITORY
    - run: |
        tree GITHUB_WORKSPACE
    - run: |
        tree HOME
