# File: .github/workflows/az_login_v2.yml

on: [push]

name: TestEnvVariable

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - run: |
        printenv  
        pwd
        printenv > test.sh
        cat test.sh
        realpath test.sh
    - name: Az cli spike
      #uses: azure/CLI@v0-beta
      uses: ./spike-az-cli_2
      with:
        inlineScript: |
          printenv