# .github/workflows/workflow.yml
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Hellow world action step
      uses: jalajmsft/test-action@280aee4
      with:
        who-to-greet: 'let see'
      id: hello
    - run: echo "The time was ${{ steps.hello.outputs.time }}"